eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9761/eureka/
  instance:
    prefer-ip-address: true
#    ip-address: ${spring.cloud.client.ipAddress}
    appname: service-consumer-feign #swaggerui 集成时会遇到的问题    写appname后不会有 还没测试 待验证
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html #默认是 http://localhost:${server.port}/info
server:
  port: 9765
spring:
  application:
    name: service-consumer-feign

apollo.bootstrap.enabled: true
apollo.bootstrap.namespaces: pbssetting,application